<?php declare(strict_types=1);

namespace Eventbrite\Model\Enum;

/**
 * EnumType: member
 *
 * @method static AGE_RESTRICTION_ALL_AGES(): string
 * @method static AGE_RESTRICTION_MIN_TWELVE(): string
 * @method static AGE_RESTRICTION_MIN_THIRTEEN(): string
 * @method static AGE_RESTRICTION_MIN_FOURTEEN(): string
 * @method static AGE_RESTRICTION_MIN_FIFTEEN(): string
 * @method static AGE_RESTRICTION_MIN_SIXTEEN(): string
 * @method static AGE_RESTRICTION_MIN_SEVENTEEN(): string
 * @method static AGE_RESTRICTION_MIN_EIGHTEEN(): string
 * @method static AGE_RESTRICTION_MIN_NINETEEN(): string
 * @method static AGE_RESTRICTION_MIN_TWENTY_ONE(): string
 * @method static AGE_RESTRICTION_UNDER_TWENTY_ONE_WITH_GUARDIAN(): string
 * @method static AGE_RESTRICTION_UNDER_EIGHTEEN_WITH_GUARDIAN(): string
 */
final class VenueBaseAgeRestriction extends \MyCLabs\Enum\Enum
{
    private const AGE_RESTRICTION_ALL_AGES = 'AGE_RESTRICTION_ALL_AGES';
    private const AGE_RESTRICTION_MIN_TWELVE = 'AGE_RESTRICTION_MIN_TWELVE';
    private const AGE_RESTRICTION_MIN_THIRTEEN = 'AGE_RESTRICTION_MIN_THIRTEEN';
    private const AGE_RESTRICTION_MIN_FOURTEEN = 'AGE_RESTRICTION_MIN_FOURTEEN';
    private const AGE_RESTRICTION_MIN_FIFTEEN = 'AGE_RESTRICTION_MIN_FIFTEEN';
    private const AGE_RESTRICTION_MIN_SIXTEEN = 'AGE_RESTRICTION_MIN_SIXTEEN';
    private const AGE_RESTRICTION_MIN_SEVENTEEN = 'AGE_RESTRICTION_MIN_SEVENTEEN';
    private const AGE_RESTRICTION_MIN_EIGHTEEN = 'AGE_RESTRICTION_MIN_EIGHTEEN';
    private const AGE_RESTRICTION_MIN_NINETEEN = 'AGE_RESTRICTION_MIN_NINETEEN';
    private const AGE_RESTRICTION_MIN_TWENTY_ONE = 'AGE_RESTRICTION_MIN_TWENTY_ONE';
    private const AGE_RESTRICTION_UNDER_TWENTY_ONE_WITH_GUARDIAN = 'AGE_RESTRICTION_UNDER_TWENTY_ONE_WITH_GUARDIAN';
    private const AGE_RESTRICTION_UNDER_EIGHTEEN_WITH_GUARDIAN = 'AGE_RESTRICTION_UNDER_EIGHTEEN_WITH_GUARDIAN';
}
